version: '3'
services:
  toxiproxy:
    image: "shopify/toxiproxy"
    ports:
       - "8474:8474"
       - "13306:3306"
  # We created proxy configuration from another ephermal container
  toxiproxy-config:
    image: "shopify/toxiproxy"
    entrypoint: > 
      sh -c "/go/bin/toxiproxy-cli -h toxiproxy:8474 create mysql --listen 0.0.0.0:3306 --upstream mysql:3306;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create redis-master --listen 0.0.0.0:6379 --upstream redis-master:6379;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create redis-slave --listen 0.0.0.0:16379 --upstream redis-slave:6379"
  redis-master:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-slave:
    image: "redis:alpine"
    ports:
      - "16379:6379"
    command: redis-server --slaveof redis-master 6379
  mysql:
    image: mysql:5.6
    ports:
    - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "letmein"
    volumes:
      - /var/lib/mysql
  
  ## User service creation is disabled for now
  # user-servce:
  #   build: "app"
  #   ports:
  #      - "8080:8080"
