version: '3'
services:
  toxiproxy:
    image: "shopify/toxiproxy"
    ports:
       - "8474:8474"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.6
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "letmein"
